version: "3.9"
services:
  postgres:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8888:8888"
    environment:
      - DB_SOURCE=postgresql://root:password@postgres16:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis
    entrypoint: 
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "app/start.sh"
      ]
    command: [ "/app/main" ]